server:
  port: 8080
  servlet:
    context-path: /

spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://120.27.231.25:3306/ddcghjpt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
    initialSize: 5
    minIdle: 10
    maxActive: 20
    maxWait: 60000
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    protocol: smtp
    username: 1964682912@qq.com
    password: wqpktoqwakuvfchd
  smtp:
    auth: true
    starttls:
      enable: true
      required: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
mybatis:
  typeAliasesPackage: com.edu.zut.rwdb.system.**.domain
  mapper-locations: classpath:mybatis.*.xml
  type-aliases-package: com.edu.zut.rwdb.system.**.domain
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# Shiro
shiro:
  user:
    loginUrl: /login
    unauthorizedUrl: /unauth
    indexUrl: /index
    captchaEnabled: true
    captchaType: math
  cookie:
    domain:
    path: /
    httpOnly: true
    maxAge: 30
  session:
    expireTime: 30
    dbSyncPeriod: 1
    validationInterval: 1
    maxSession: -1
    kickoutAfter: false

