server:
  port: 8080
  servlet:
    context-path: /

spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@47.99.46.85:1521:orcl
    data-username: sys
    password: 123456

  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    protocol: smtp
    username: 1964682912@qq.com
    password: wqpktoqwakuvfchd
  smtp:
    auth: true
    starttls:
      enable: true
      required: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
mybatis:
  typeAliasesPackage: com.edu.zut.rwdb.system.**.domain
  mapper-locations: classpath:mybatis.*.xml
  type-aliases-package: com.edu.zut.rwdb.system.**.domain
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# Shiro
shiro:
  user:
    loginUrl: /login
    unauthorizedUrl: /unauth
    indexUrl: /index
    captchaEnabled: true
    captchaType: math
  cookie:
    domain:
    path: /
    httpOnly: true
    maxAge: 30
  session:
    expireTime: 30
    dbSyncPeriod: 1
    validationInterval: 1
    maxSession: -1
    kickoutAfter: false

